backend:
  name: git-gateway
  branch: main

media_folder: "resources"
public_folder: "/resources"

collections:
  - name: "posts"
    label: "文章"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "正文", name: "body", widget: "markdown" }
