backend:
  name: github
  repo: https://xauusd-room.github.io/EA/
  branch: main


media_folder: "resources"
public_folder: "/resources"

collections:
  - name: "posts"
    label: "文章"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"

    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "简介", name: "description", widget: "text"}
      - {label: "发布时间", name: "date", widget: "datetime"}
      - {label: "封面图", name: "thumbnail", widget: "image"}
      - {label: "正文", name: "body", widget: "markdown"}
